### ISSUE TITLE
No habre en Huayra 4

### ISSUE THREAD

**Issue by santiagoarmas** [HuayraLinux/huayra-tda#11]
Eso mismo, no habre en Huayra 4

**Comment by ftoledo** [comment]
Si lo ejecutas desde la terminal te tira algun error?

**Comment by santiagoarmas** [comment]
root@huayra4:/home/alumno# huayra-tda-player 
Traceback (most recent call last):
  File "/usr/bin/huayra-tda-player", line 448, in <module>
    proc = subprocess.Popen(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ftoledo** [comment]
Duplicado de #10
